# Generated by Django 5.1.4 on 2024-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_todo', models.CharField(max_length=30)),
                ('ent_type', models.CharField(max_length=50)),
            ],
        ),
    ]
