# Generated by Django 5.1.4 on 2024-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='primaryalert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='form',
        ),
    ]
